version: '3'

services:
    reverse-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: reverse-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:ro
            - nginx-static:/usr/share/nginx/html
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ''
        networks:
            - proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - nginx-static:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
        depends_on:
            - reverse-proxy

networks:
    proxy:

volumes:
    certs:
    nginx-static:
    vhost: